### ISSUE TITLE
Please document the exact SHA of `atd` in use

### ISSUE THREAD

**Issue by dysinger** [ahrefs/bs-atdgen-codec-runtime#4]
I've recently upgraded bs-atdgen-codec-runtime & atd and the code generated from master `atd` doesn't work anymore.

```
  We've found a bug for you!
  /home/tim/src/pt/all/swage/web/src/Types_bs.ml 121:39-84
  
  119 │ )
  120 │ let write_zt_network = (
  121 │   Atdgen_codec_runtime.Encode.adapter Atdgen_runtime.Json_adapter.Typ
        e_field.restore (
  122 │     Atdgen_codec_runtime.Encode.make (fun (t : zt_network) ->
  123 │       (
  
  The module or file Atdgen_runtime can't be found.
  - If it's a third-party dependency:
    - Did you list it in bsconfig.json?
    - Did you run `bsb` instead of `bsb -make-world`
      (latter builds third-parties)?
  - Did you include the file's directory in bsconfig.json?
```

**Comment by Khady** [comment]
Can you give the exact version of atd you are using? And a small example to reproduce? I am a bit surprised, because we are using the master version of atd with bs-atdgen-codec-runtime 1.1.0 too and no problem here.

**Comment by dysinger** [comment]
I'm using master (today) of atd with bs-atdgen-codec-runtime 1.1.0

**Comment by dysinger** [comment]
Ahha! I had a <json adapter.ocaml="Atdgen_runtime.Json_adapter.Type_field"> in my atd file (old style)

**Comment by dysinger** [comment]
Even though I figured out my mistake, it still might be handy to note which version of master goes with each release (while we are in this state of limbo where atd isn't released yet.)

**Comment by Khady** [comment]
Glad to know it works for you. You are right, I will add a note about which atd version we know is working.
